name: Deploy static app to Azure Web App - innovate-with-ai-in-lowcode

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Compress the static files for deployment
      - name: Zip static files
        run: zip -r release.zip ./*

      # Step 3: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D8FEF2F00B8D4A1180C4B670D1E0AB5B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4886D115C8A046E29B54EDE7CF989EDC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7B4834DE929C4EA395E28E673AEE07CA }}

      # Step 4: Deploy the static files to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'innovate-with-ai-in-lowcode'
          slot-name: 'production'
          package: release.zip
